
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/galaxy
    username: root
    password: shraddha#19
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: false
    properties:
      hibernate:
      format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

server:
  port: 9090